/* ============================================================
   data.js — ไฟล์ข้อมูลและการตั้งค่า
   ------------------------------------------------------------
   ไฟล์นี้คือไฟล์เดียวที่คุณต้องแก้ ไม่ต้องแตะ app.js
   แก้คำพูด แก้ชื่อภาษาไทย เพิ่มสี ปรับความไว ทำได้ที่นี่ทั้งหมด
   ============================================================ */

/* ---------- 1. การตั้งค่าหลัก ---------- */
const CONFIG = {
  // ความเชื่อมั่นขั้นต่ำที่จะยอมพูด
  // ต่ำ = พูดเยอะ แต่ผิดบ่อย / สูง = พูดน้อย แต่แม่น
  minScore: 0.62,

  // เว้นช่วงระหว่างการตรวจจับ (มิลลิวินาที)
  // 400 = ตรวจ 2.5 ครั้งต่อวินาที เพียงพอและไม่กินแบต
  detectInterval: 400,

  // เว้นช่วงขั้นต่ำก่อนพูดวัตถุเดิมซ้ำ (มิลลิวินาที)
  // กันไม่ให้พูดวนซ้ำจนน่ารำคาญ
  repeatCooldown: 6000,

  // จำนวนวัตถุสูงสุดที่พูดต่อครั้งในโหมดอัตโนมัติ
  maxSpeakAuto: 2,

  // จำนวนวัตถุสูงสุดที่พูดเมื่อผู้ใช้แตะจอ
  maxSpeakTap: 4,

  // ความเร็วเสียงพูด 0.5 ถึง 2.0
  speechRate: 1.05,

  // สั่นเมื่อเจอวัตถุใหม่ (มิลลิวินาที) ตั้ง 0 เพื่อปิด
  vibrateMs: 40,

  // ต่ำกว่านี้จะพูดนำหน้าว่า "น่าจะเป็น" เพื่อบอกว่าไม่มั่นใจ
  unsureBelow: 0.72,

  // กรอบคลาสเดียวกันที่ทับกันเกินค่านี้ ถือว่าเป็นวัตถุเดียวกัน
  dedupeIoU: 0.55,

  // โมเดลที่ใช้ เลือกได้ 3 แบบ
  //   lite_mobilenet_v2 = เร็วสุด แม่นน้อยสุด
  //   mobilenet_v2      = แม่นขึ้น ช้าลงราว 40%   <- ใช้อยู่
  //   mobilenet_v1      = อยู่ตรงกลาง
  modelBase: "mobilenet_v2",
};

/* ---------- 2. ชื่อวัตถุภาษาไทย (COCO 80 คลาส) ----------
   ซ้ายคือชื่อที่โมเดลส่งกลับมา ห้ามแก้
   ขวาคือคำที่จะพูด แก้ได้ตามต้องการ                        */
const TH_LABELS = {
  "person": "คน",
  "bicycle": "จักรยาน",
  "car": "รถยนต์",
  "motorcycle": "รถจักรยานยนต์",
  "airplane": "เครื่องบิน",
  "bus": "รถบัส",
  "train": "รถไฟ",
  "truck": "รถบรรทุก",
  "boat": "เรือ",
  "traffic light": "สัญญาณไฟจราจร",
  "fire hydrant": "หัวจ่ายน้ำดับเพลิง",
  "stop sign": "ป้ายหยุด",
  "parking meter": "มิเตอร์จอดรถ",
  "bench": "ม้านั่ง",
  "bird": "นก",
  "cat": "แมว",
  "dog": "สุนัข",
  "horse": "ม้า",
  "sheep": "แกะ",
  "cow": "วัว",
  "elephant": "ช้าง",
  "bear": "หมี",
  "zebra": "ม้าลาย",
  "giraffe": "ยีราฟ",
  "backpack": "เป้สะพายหลัง",
  "umbrella": "ร่ม",
  "handbag": "กระเป๋าถือ",
  "tie": "เนกไท",
  "suitcase": "กระเป๋าเดินทาง",
  "frisbee": "จานร่อน",
  "skis": "สกี",
  "snowboard": "สโนว์บอร์ด",
  "sports ball": "ลูกบอล",
  "kite": "ว่าว",
  "baseball bat": "ไม้เบสบอล",
  "baseball glove": "ถุงมือเบสบอล",
  "skateboard": "สเก็ตบอร์ด",
  "surfboard": "กระดานโต้คลื่น",
  "tennis racket": "ไม้เทนนิส",
  "bottle": "ขวด",
  "wine glass": "แก้วไวน์",
  "cup": "แก้วน้ำ",
  "fork": "ส้อม",
  "knife": "มีด",
  "spoon": "ช้อน",
  "bowl": "ชาม",
  "banana": "กล้วย",
  "apple": "แอปเปิล",
  "sandwich": "แซนด์วิช",
  "orange": "ส้ม",
  "broccoli": "บรอกโคลี",
  "carrot": "แครอท",
  "hot dog": "ฮอทดอก",
  "pizza": "พิซซ่า",
  "donut": "โดนัท",
  "cake": "เค้ก",
  "chair": "เก้าอี้",
  "couch": "โซฟา",
  "potted plant": "กระถางต้นไม้",
  "bed": "เตียง",
  "dining table": "โต๊ะอาหาร",
  "toilet": "โถส้วม",
  "tv": "โทรทัศน์",
  "laptop": "โน้ตบุ๊ก",
  "mouse": "เมาส์",
  "remote": "รีโมท",
  "keyboard": "คีย์บอร์ด",
  "cell phone": "โทรศัพท์มือถือ",
  "microwave": "ไมโครเวฟ",
  "oven": "เตาอบ",
  "toaster": "เครื่องปิ้งขนมปัง",
  "sink": "อ่างล้างมือ",
  "refrigerator": "ตู้เย็น",
  "book": "หนังสือ",
  "clock": "นาฬิกา",
  "vase": "แจกัน",
  "scissors": "กรรไกร",
  "teddy bear": "ตุ๊กตาหมี",
  "hair drier": "ไดร์เป่าผม",
  "toothbrush": "แปรงสีฟัน",
};

/* ---------- 3. วัตถุที่ควรเตือนเป็นพิเศษ ----------
   วัตถุอันตรายหรือสำคัญ จะถูกพูดก่อนวัตถุอื่นเสมอ
   และมีคำเตือนนำหน้า                                    */
const PRIORITY = {
  "person": "ระวัง มี",
  "car": "ระวัง มี",
  "motorcycle": "ระวัง มี",
  "bicycle": "ระวัง มี",
  "bus": "ระวัง มี",
  "truck": "ระวัง มี",
  "dog": "ระวัง มี",
  "knife": "ระวัง มี",
  "stop sign": "",
  "traffic light": "",
};

/* ---------- 4. ชื่อสีภาษาไทย ----------
   แต่ละสีกำหนดด้วยช่วงค่า Hue (0-360), Saturation, Value
   ปรับได้ถ้าเห็นว่าเรียกสีผิดบ่อย                        */
const COLORS = [
  { name: "สีดำ",      vMax: 0.18 },
  { name: "สีขาว",     sMax: 0.10, vMin: 0.85 },
  { name: "สีเทา",     sMax: 0.12 },
  { name: "สีครีม",    hMin: 20,  hMax: 60,  sMax: 0.32, vMin: 0.68 },
  { name: "สีน้ำตาล",  hMin: 8,   hMax: 45,  vMax: 0.70, sMax: 0.72 },
  { name: "สีแดง",     hMin: 345, hMax: 360 },
  { name: "สีแดง",     hMin: 0,   hMax: 12 },
  { name: "สีส้ม",     hMin: 12,  hMax: 40 },
  { name: "สีเหลือง",  hMin: 40,  hMax: 68 },
  { name: "สีเขียว",   hMin: 68,  hMax: 160 },
  { name: "สีฟ้า",     hMin: 160, hMax: 200 },
  { name: "สีน้ำเงิน", hMin: 200, hMax: 255 },
  { name: "สีม่วง",    hMin: 255, hMax: 290 },
  { name: "สีชมพู",    hMin: 290, hMax: 345 },
];

/* ---------- 4.1 คลาสที่ไม่บอกสี ----------
   บอกสีผิวคนไม่มีประโยชน์และไม่เหมาะสม
   สัตว์มีลายหลายสี บอกสีเดียวมักผิด                        */
const NO_COLOR = ["person", "cat", "dog", "bird", "horse", "sheep", "cow"];

/* ---------- 5. คำบอกตำแหน่งและระยะ ---------- */
const POSITION = {
  left:   "ทางซ้าย",
  center: "ตรงหน้า",
  right:  "ทางขวา",
};

// เกณฑ์ตัดสินระยะจากสัดส่วนพื้นที่ที่วัตถุกินในเฟรม
const DISTANCE = [
  { maxArea: 0.05, text: "ระยะไกล" },
  { maxArea: 0.22, text: "ระยะกลาง" },
  { maxArea: 1.00, text: "ระยะใกล้" },
];

/* ---------- 6. ข้อความของระบบ ---------- */
const MESSAGES = {
  ready:      "พร้อมใช้งานแล้ว แตะที่หน้าจอเพื่อให้บอกสิ่งที่เห็น หรือกดปุ่มโหมดอัตโนมัติ",
  loading:    "กำลังโหลดระบบ กรุณารอสักครู่",
  cameraOn:   "เปิดกล้องแล้ว",
  cameraFail: "ไม่สามารถเปิดกล้องได้ กรุณาอนุญาตการใช้กล้องในเบราว์เซอร์",
  autoOn:     "เปิดโหมดพูดอัตโนมัติ",
  autoOff:    "ปิดโหมดพูดอัตโนมัติ",
  nothing:    "ไม่พบสิ่งของ",
  modelFail:  "โหลดโมเดลไม่สำเร็จ กรุณาตรวจสอบการเชื่อมต่ออินเทอร์เน็ตแล้วรีเฟรช",
  unsure:     "น่าจะเป็น",

  // ข้อความสอนใช้งาน พูดหลังเริ่มระบบครั้งแรก
  welcome:    "ยินดีต้อนรับสู่ตาทิพย์ ผู้ช่วยบอกสิ่งของรอบตัว",
  tutorial: [
    "วิธีใช้งานมีสามอย่าง",
    "หนึ่ง แตะกลางหน้าจอหนึ่งครั้ง เพื่อให้บอกสิ่งที่เห็นตรงหน้า",
    "สอง ด้านล่างมีปุ่มสี่ปุ่มเรียงเป็นสองแถว แถวบนซ้ายคือหยุด แถวบนขวาคือโหมดอัตโนมัติ แถวล่างซ้ายคือเปลี่ยนโหมดการตรวจจับ แถวล่างขวาคือช่วยเหลือ",
    "สาม แตะปุ่มค้างไว้เพื่อฟังชื่อปุ่ม แล้วยกนิ้วขึ้นเพื่อกด ถ้าไม่ต้องการกด ให้เลื่อนนิ้วออกจากปุ่มก่อนยก",
    "เมื่อเปิดโหมดอัตโนมัติ ระบบจะพูดบอกเองเมื่อพบสิ่งของใหม่ โดยไม่ต้องแตะ",
    "ยกโทรศัพท์ขึ้นให้กล้องหันไปทางที่ต้องการ แล้วเริ่มใช้งานได้เลย",
  ],
  tapToStart: "แตะที่ใดก็ได้บนหน้าจอเพื่อเริ่มใช้งาน",
  btnStop:    "ปุ่มหยุดการทำงาน",
  btnAuto:    "ปุ่มโหมดอัตโนมัติ",
  btnMode:    "ปุ่มเปลี่ยนโหมด",
  btnHelp:    "ปุ่มช่วยเหลือ ฟังวิธีใช้งานอีกครั้ง",
};

/* ---------- 7. โหมดการทำงาน ----------
   ปุ่ม "โหมด" จะวนสลับตามลำดับในรายการนี้
   type "detect"   = ตรวจจับวัตถุ บอกตำแหน่งได้ แต่รู้จักแค่ 80 ชนิด
   type "classify" = จำแนกทั้งภาพ รู้จัก 1000 ชนิด แต่บอกตำแหน่งไม่ได้    */
const MODES = [
  {
    id: "fast", type: "detect", base: "lite_mobilenet_v2",
    label: "โหมดเร็ว",
    say: "โหมดเร็ว รู้จักแปดสิบชนิด บอกตำแหน่งได้ ทำงานเร็วที่สุด",
  },
  {
    id: "balanced", type: "detect", base: "mobilenet_v1",
    label: "โหมดสมดุล",
    say: "โหมดสมดุล รู้จักแปดสิบชนิด บอกตำแหน่งได้ ความเร็วปานกลาง",
  },
  {
    id: "accurate", type: "detect", base: "mobilenet_v2",
    label: "โหมดแม่นยำ",
    say: "โหมดแม่นยำ รู้จักแปดสิบชนิด บอกตำแหน่งได้ แม่นที่สุดแต่ช้าที่สุด",
  },
  {
    id: "wide", type: "classify", base: null,
    label: "โหมดคำศัพท์กว้าง",
    say: "โหมดคำศัพท์กว้าง รู้จักหนึ่งพันชนิด แต่บอกตำแหน่งไม่ได้ ให้เล็งวัตถุไว้กลางหน้าจอ",
  },
];

// โหมดเริ่มต้นเมื่อเปิดแอป อ้างตาม id ด้านบน
const DEFAULT_MODE = "accurate";

/* ---------- 8. คำแปลไทยของ ImageNet (ใช้ในโหมดคำศัพท์กว้าง) ----------
   ImageNet มี 1000 ชนิด แปลไว้เฉพาะที่พบในชีวิตประจำวัน
   ชนิดที่ไม่ได้แปลจะแสดงเป็นภาษาอังกฤษ                                  */
const IMAGENET_TH = {
  "abacus": "ลูกคิด",
  "abaya": "เสื้อคลุม",
  "acorn squash": "ฟักทอง",
  "acoustic guitar": "กีตาร์โปร่ง",
  "ambulance": "รถพยาบาล",
  "analog clock": "นาฬิกาเข็ม",
  "ashcan": "ถังขยะ",
  "backpack": "เป้สะพายหลัง",
  "bagel": "เบเกิล",
  "bakery": "ร้านเบเกอรี่",
  "balloon": "ลูกโป่ง",
  "ballpoint": "ปากกาลูกลื่น",
  "banana": "กล้วย",
  "band aid": "พลาสเตอร์ยา",
  "bannister": "ราวบันได",
  "barbell": "บาร์เบล",
  "barber chair": "เก้าอี้ตัดผม",
  "barbershop": "ร้านตัดผม",
  "barrel": "ถัง",
  "baseball": "ลูกเบสบอล",
  "basketball": "ลูกบาสเกตบอล",
  "bath towel": "ผ้าเช็ดตัว",
  "bathing cap": "หมวกว่ายน้ำ",
  "bathtub": "อ่างอาบน้ำ",
  "beach wagon": "รถสเตชันแวกอน",
  "beagle": "สุนัขบีเกิล",
  "beer bottle": "ขวดเบียร์",
  "beer glass": "แก้วเบียร์",
  "bell pepper": "พริกหวาน",
  "belt": "เข็มขัด",
  "bib": "ผ้ากันเปื้อนเด็ก",
  "bicycle-built-for-two": "จักรยานสองที่นั่ง",
  "binder": "แฟ้ม",
  "birdhouse": "บ้านนก",
  "book jacket": "ปกหนังสือ",
  "bookcase": "ชั้นหนังสือ",
  "bookshop": "ร้านหนังสือ",
  "bow tie": "หูกระต่าย",
  "brassiere": "เสื้อชั้นใน",
  "broccoli": "บรอกโคลี",
  "broom": "ไม้กวาด",
  "bucket": "ถัง",
  "burrito": "เบอร์ริโต",
  "butternut squash": "ฟักทอง",
  "cab": "รถแท็กซี่",
  "caldron": "หม้อใบใหญ่",
  "can opener": "ที่เปิดกระป๋อง",
  "candle": "เทียน",
  "carbonara": "พาสต้าคาโบนารา",
  "cardigan": "เสื้อคาร์ดิแกน",
  "carton": "กล่องกระดาษ",
  "cassette": "เทปคาสเซ็ต",
  "cassette player": "เครื่องเล่นเทป",
  "cauliflower": "กะหล่ำดอก",
  "cd player": "เครื่องเล่นซีดี",
  "cellular telephone": "โทรศัพท์มือถือ",
  "chain": "โซ่",
  "chainlink fence": "รั้วลวดตาข่าย",
  "cheeseburger": "ชีสเบอร์เกอร์",
  "chest": "หีบ",
  "chiffonier": "ตู้ลิ้นชัก",
  "chihuahua": "สุนัขชิวาวา",
  "china cabinet": "ตู้โชว์",
  "chocolate sauce": "ซอสช็อกโกแลต",
  "cleaver": "มีดอีโต้",
  "clog": "รองเท้าไม้",
  "cock": "ไก่ตัวผู้",
  "cocktail shaker": "เชคเกอร์",
  "coffee mug": "แก้วกาแฟ",
  "coffeepot": "กากาแฟ",
  "combination lock": "กุญแจรหัส",
  "comic book": "หนังสือการ์ตูน",
  "common iguana": "อิกัวนา",
  "computer keyboard": "คีย์บอร์ด",
  "confectionery": "ร้านขนม",
  "convertible": "รถเปิดประทุน",
  "corkscrew": "ที่เปิดขวดไวน์",
  "corn": "ข้าวโพด",
  "cowboy boot": "รองเท้าบูท",
  "cowboy hat": "หมวกคาวบอย",
  "crib": "เปลเด็ก",
  "crock pot": "หม้อตุ๋น",
  "crossword puzzle": "ปริศนาอักษรไขว้",
  "cucumber": "แตงกวา",
  "cup": "ถ้วย",
  "custard apple": "น้อยหน่า",
  "desk": "โต๊ะทำงาน",
  "desktop computer": "คอมพิวเตอร์ตั้งโต๊ะ",
  "diaper": "ผ้าอ้อม",
  "digital clock": "นาฬิกาดิจิทัล",
  "digital watch": "นาฬิกาข้อมือ",
  "dining table": "โต๊ะอาหาร",
  "dishwasher": "เครื่องล้างจาน",
  "doormat": "พรมเช็ดเท้า",
  "dough": "แป้งโด",
  "dumbbell": "ดัมเบล",
  "dutch oven": "หม้อ",
  "eggnog": "เครื่องดื่มไข่",
  "egyptian cat": "แมว",
  "electric fan": "พัดลมไฟฟ้า",
  "electric guitar": "กีตาร์ไฟฟ้า",
  "entertainment center": "ชั้นวางทีวี",
  "envelope": "ซองจดหมาย",
  "espresso": "กาแฟเอสเพรสโซ",
  "espresso maker": "เครื่องชงกาแฟ",
  "face powder": "แป้งทาหน้า",
  "fig": "มะเดื่อ",
  "file": "ตู้เอกสาร",
  "fire engine": "รถดับเพลิง",
  "fire hydrant": "หัวจ่ายน้ำดับเพลิง",
  "fire screen": "ฉากกั้น",
  "flagpole": "เสาธง",
  "flashlight": "ไฟฉาย",
  "folding chair": "เก้าอี้พับ",
  "forklift": "รถโฟล์คลิฟท์",
  "fountain pen": "ปากกาหมึกซึม",
  "four-poster": "เตียงเสาสูง",
  "french loaf": "ขนมปังฝรั่งเศส",
  "frying pan": "กระทะ",
  "garbage truck": "รถขยะ",
  "gecko": "จิ้งจก",
  "goblet": "แก้วมีก้าน",
  "golden retriever": "สุนัขโกลเด้น",
  "goldfish": "ปลาทอง",
  "golf ball": "ลูกกอล์ฟ",
  "golfcart": "รถกอล์ฟ",
  "gown": "ชุดราตรี",
  "grand piano": "เปียโน",
  "granny smith": "แอปเปิลเขียว",
  "grocery store": "ร้านขายของชำ",
  "guacamole": "กวาคาโมเล",
  "hair slide": "กิ๊บติดผม",
  "hair spray": "สเปรย์จัดแต่งผม",
  "hammer": "ค้อน",
  "hamper": "ตะกร้าผ้า",
  "hand blower": "ไดร์เป่าผม",
  "handkerchief": "ผ้าเช็ดหน้า",
  "hard disc": "ฮาร์ดดิสก์",
  "head cabbage": "กะหล่ำปลี",
  "hen": "ไก่",
  "home theater": "โฮมเธียเตอร์",
  "hotdog": "ฮอทดอก",
  "ice cream": "ไอศกรีม",
  "ice lolly": "ไอติมแท่ง",
  "ipod": "เครื่องเล่นเพลง",
  "iron": "เตารีด",
  "jackfruit": "ขนุน",
  "jean": "กางเกงยีนส์",
  "jeep": "รถจี๊ป",
  "jersey": "เสื้อยืด",
  "joystick": "จอยสติ๊ก",
  "kimono": "กิโมโน",
  "labrador retriever": "สุนัขลาบราดอร์",
  "ladle": "ทัพพี",
  "lampshade": "โคมไฟ",
  "laptop": "โน้ตบุ๊ก",
  "lemon": "มะนาว",
  "lighter": "ไฟแช็ก",
  "limousine": "รถลีมูซีน",
  "lipstick": "ลิปสติก",
  "loafer": "รองเท้าหนัง",
  "lotion": "โลชั่น",
  "loudspeaker": "ลำโพง",
  "magnetic compass": "เข็มทิศ",
  "mailbox": "ตู้ไปรษณีย์",
  "mask": "หน้ากาก",
  "matchstick": "ไม้ขีดไฟ",
  "measuring cup": "ถ้วยตวง",
  "meat loaf": "มีตโลฟ",
  "medicine chest": "ตู้ยา",
  "menu": "เมนู",
  "microphone": "ไมโครโฟน",
  "microwave": "ไมโครเวฟ",
  "minibus": "รถมินิบัส",
  "miniskirt": "กระโปรงสั้น",
  "minivan": "รถตู้",
  "mitten": "ถุงมือ",
  "mixing bowl": "ชามผสม",
  "modem": "โมเด็ม",
  "monitor": "จอภาพ",
  "mop": "ไม้ถูพื้น",
  "moped": "รถมอเตอร์ไซค์",
  "mosquito net": "มุ้ง",
  "motor scooter": "รถสกูตเตอร์",
  "motorcycle": "รถจักรยานยนต์",
  "mountain bike": "จักรยานเสือภูเขา",
  "mouse": "เมาส์",
  "mushroom": "เห็ด",
  "nail": "ตะปู",
  "necklace": "สร้อยคอ",
  "nipple": "จุกนม",
  "notebook": "โน้ตบุ๊ก",
  "orange": "ส้ม",
  "oxygen mask": "หน้ากากออกซิเจน",
  "packet": "ซอง",
  "padlock": "แม่กุญแจ",
  "paper towel": "กระดาษเช็ดมือ",
  "park bench": "ม้านั่ง",
  "parking meter": "มิเตอร์จอดรถ",
  "pencil box": "กล่องดินสอ",
  "pencil sharpener": "กบเหลาดินสอ",
  "perfume": "น้ำหอม",
  "persian cat": "แมวเปอร์เซีย",
  "photocopier": "เครื่องถ่ายเอกสาร",
  "picket fence": "รั้วไม้",
  "pickup": "รถกระบะ",
  "pill bottle": "ขวดยา",
  "pillow": "หมอน",
  "pineapple": "สับปะรด",
  "ping-pong ball": "ลูกปิงปอง",
  "pinwheel": "กังหันลม",
  "pitcher": "เหยือก",
  "pizza": "พิซซ่า",
  "plastic bag": "ถุงพลาสติก",
  "plate": "จาน",
  "plunger": "ที่ปั๊มส้วม",
  "police van": "รถตำรวจ",
  "pomegranate": "ทับทิม",
  "pomeranian": "สุนัขปอมเมอเรเนียน",
  "pop bottle": "ขวดน้ำอัดลม",
  "pot": "กระถางต้นไม้",
  "power drill": "สว่านไฟฟ้า",
  "prayer rug": "พรม",
  "pretzel": "เพรตเซล",
  "printer": "เครื่องพิมพ์",
  "projector": "เครื่องฉายภาพ",
  "pug": "สุนัขปั๊ก",
  "purse": "กระเป๋าถือ",
  "quill": "ปากกาขนนก",
  "quilt": "ผ้านวม",
  "racer": "รถแข่ง",
  "racket": "ไม้แร็กเกต",
  "radio": "วิทยุ",
  "red wine": "ไวน์แดง",
  "refrigerator": "ตู้เย็น",
  "remote control": "รีโมท",
  "restaurant": "ร้านอาหาร",
  "rocking chair": "เก้าอี้โยก",
  "rotisserie": "เตาย่าง",
  "rubber": "ยาง",
  "rubber eraser": "ยางลบ",
  "rule": "ไม้บรรทัด",
  "running shoe": "รองเท้าผ้าใบ",
  "safe": "ตู้เซฟ",
  "safety pin": "เข็มกลัด",
  "salt shaker": "ขวดเกลือ",
  "sandal": "รองเท้าแตะ",
  "scale": "เครื่องชั่ง",
  "school bus": "รถโรงเรียน",
  "screen": "จอภาพ",
  "screw": "สกรู",
  "screwdriver": "ไขควง",
  "shih-tzu": "สุนัขชิสุ",
  "shopping basket": "ตะกร้า",
  "shopping cart": "รถเข็น",
  "shower curtain": "ม่านอาบน้ำ",
  "siamese cat": "แมวสยาม",
  "sliding door": "ประตูเลื่อน",
  "soap dispenser": "ที่กดสบู่",
  "soccer ball": "ลูกฟุตบอล",
  "sock": "ถุงเท้า",
  "solar dish": "จานรับแสงอาทิตย์",
  "soldering iron": "หัวแร้ง",
  "sombrero": "หมวกปีกกว้าง",
  "soup bowl": "ชามซุป",
  "space heater": "เครื่องทำความร้อน",
  "spatula": "ตะหลิว",
  "sports car": "รถสปอร์ต",
  "spotlight": "ไฟสปอตไลต์",
  "stethoscope": "หูฟังแพทย์",
  "stopwatch": "นาฬิกาจับเวลา",
  "stove": "เตา",
  "strainer": "กระชอน",
  "strawberry": "สตรอว์เบอร์รี",
  "street sign": "ป้ายถนน",
  "studio couch": "โซฟา",
  "suit": "ชุดสูท",
  "sunglass": "แว่นกันแดด",
  "sunglasses": "แว่นกันแดด",
  "sunscreen": "ครีมกันแดด",
  "sweatshirt": "เสื้อสเวตเชิ้ต",
  "swimming trunks": "กางเกงว่ายน้ำ",
  "swing": "ชิงช้า",
  "switch": "สวิตช์ไฟ",
  "syringe": "เข็มฉีดยา",
  "tabby": "แมวลาย",
  "table lamp": "โคมไฟตั้งโต๊ะ",
  "teapot": "กาน้ำชา",
  "teddy": "ตุ๊กตาหมี",
  "television": "โทรทัศน์",
  "tennis ball": "ลูกเทนนิส",
  "thimble": "ปลอกนิ้ว",
  "throne": "เก้าอี้ใหญ่",
  "tiger cat": "แมวลายเสือ",
  "toaster": "เครื่องปิ้งขนมปัง",
  "toilet seat": "ฝารองนั่งชักโครก",
  "toilet tissue": "กระดาษชำระ",
  "tow truck": "รถลาก",
  "toy poodle": "สุนัขพุดเดิ้ล",
  "toyshop": "ร้านของเล่น",
  "traffic light": "สัญญาณไฟจราจร",
  "trailer truck": "รถพ่วง",
  "tray": "ถาด",
  "tree frog": "กบต้นไม้",
  "tricycle": "รถสามล้อ",
  "trifle": "ขนมหวาน",
  "trolleybus": "รถราง",
  "tub": "อ่าง",
  "turnstile": "ประตูหมุน",
  "typewriter keyboard": "คีย์บอร์ด",
  "umbrella": "ร่ม",
  "unicycle": "จักรยานล้อเดียว",
  "vacuum": "เครื่องดูดฝุ่น",
  "vase": "แจกัน",
  "volleyball": "ลูกวอลเลย์บอล",
  "waffle iron": "เครื่องทำวาฟเฟิล",
  "wall clock": "นาฬิกาแขวน",
  "wallet": "กระเป๋าสตางค์",
  "wardrobe": "ตู้เสื้อผ้า",
  "washbasin": "อ่างล้างหน้า",
  "washer": "เครื่องซักผ้า",
  "water bottle": "ขวดน้ำ",
  "water jug": "เหยือกน้ำ",
  "web site": "หน้าเว็บ",
  "whistle": "นกหวีด",
  "window screen": "มุ้งลวด",
  "window shade": "ม่านบังแดด",
  "windsor tie": "เนกไท",
  "wine bottle": "ขวดไวน์",
  "wok": "กระทะจีน",
  "wooden spoon": "ช้อนไม้",
  "zucchini": "บวบ",
};
